package com.finalagc.www._1_2_MySql_DB_entities;
// Generated May 19, 2023 7:19:39 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BranchDaysId generated by hbm2java
 */
@Embeddable
public class BranchDaysId  implements java.io.Serializable {


     private int branchId;
     private String day;

    public BranchDaysId() {
    }

    public BranchDaysId(int branchId, String day) {
       this.branchId = branchId;
       this.day = day;
    }
   


    @Column(name="Branch_ID", nullable=false)
    public int getBranchId() {
        return this.branchId;
    }
    
    public void setBranchId(int branchId) {
        this.branchId = branchId;
    }


    @Column(name="day", nullable=false, length=20)
    public String getDay() {
        return this.day;
    }
    
    public void setDay(String day) {
        this.day = day;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BranchDaysId) ) return false;
		 BranchDaysId castOther = ( BranchDaysId ) other; 
         
		 return (this.getBranchId()==castOther.getBranchId())
 && ( (this.getDay()==castOther.getDay()) || ( this.getDay()!=null && castOther.getDay()!=null && this.getDay().equals(castOther.getDay()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getBranchId();
         result = 37 * result + ( getDay() == null ? 0 : this.getDay().hashCode() );
         return result;
   }   


}


