package com.finalagc.www._1_2_MySql_DB_entities;
// Generated May 19, 2023 7:19:39 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BranchAddress generated by hbm2java
 */
@Entity
@Table(name="branch_address"
    ,catalog="agc_db"
)
public class BranchAddress  implements java.io.Serializable {


     private Integer brancheAddressId;
     private Branch branch;
     private String building;
     private String city;

    public BranchAddress() {
    }

    public BranchAddress(Branch branch, String building, String city) {
       this.branch = branch;
       this.building = building;
       this.city = city;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="branche_address_id", unique=true, nullable=false)
    public Integer getBrancheAddressId() {
        return this.brancheAddressId;
    }
    
    public void setBrancheAddressId(Integer brancheAddressId) {
        this.brancheAddressId = brancheAddressId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Branch_ID", nullable=false)
    public Branch getBranch() {
        return this.branch;
    }
    
    public void setBranch(Branch branch) {
        this.branch = branch;
    }

    
    @Column(name="Building", nullable=false, length=100)
    public String getBuilding() {
        return this.building;
    }
    
    public void setBuilding(String building) {
        this.building = building;
    }

    
    @Column(name="City", nullable=false, length=45)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }




}


