package com.finalagc.www._1_2_MySql_DB_entities;
// Generated May 19, 2023 7:19:39 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Machine generated by hbm2java
 */
@Entity
@Table(name="machine"
    ,catalog="agc_db"
    , uniqueConstraints = {@UniqueConstraint(columnNames="Machine_name"), @UniqueConstraint(columnNames="Machine_type")} 
)
public class Machine  implements java.io.Serializable {


     private Integer machineId;
     private Corners corners;
     private String machineName;
     private String machineType;
     private float machinePrice;
     private int totalNumberOfPrizes;
     private Date dateOfEntry;
     private Date dateOfUpload;
     private String machineStatues;
     private float usageFees;
     private float machineReturnsMoney;
     private Float totalTimeOfUse;
     private Set<Prizes> prizeses = new HashSet<Prizes>(0);
     private Set<LsLifted> lsLifteds = new HashSet<LsLifted>(0);
     private Set<Repair> repairs = new HashSet<Repair>(0);
     private Set<PermittedMachine> permittedMachines = new HashSet<PermittedMachine>(0);
     private Set<UserUseMachine> userUseMachines = new HashSet<UserUseMachine>(0);

    public Machine() {
    }

	
    public Machine(Corners corners, String machineName, String machineType, float machinePrice, int totalNumberOfPrizes, Date dateOfEntry, Date dateOfUpload, String machineStatues, float usageFees, float machineReturnsMoney) {
        this.corners = corners;
        this.machineName = machineName;
        this.machineType = machineType;
        this.machinePrice = machinePrice;
        this.totalNumberOfPrizes = totalNumberOfPrizes;
        this.dateOfEntry = dateOfEntry;
        this.dateOfUpload = dateOfUpload;
        this.machineStatues = machineStatues;
        this.usageFees = usageFees;
        this.machineReturnsMoney = machineReturnsMoney;
    }
    public Machine(Corners corners, String machineName, String machineType, float machinePrice, int totalNumberOfPrizes, Date dateOfEntry, Date dateOfUpload, String machineStatues, float usageFees, float machineReturnsMoney, Float totalTimeOfUse, Set<Prizes> prizeses, Set<LsLifted> lsLifteds, Set<Repair> repairs, Set<PermittedMachine> permittedMachines, Set<UserUseMachine> userUseMachines) {
       this.corners = corners;
       this.machineName = machineName;
       this.machineType = machineType;
       this.machinePrice = machinePrice;
       this.totalNumberOfPrizes = totalNumberOfPrizes;
       this.dateOfEntry = dateOfEntry;
       this.dateOfUpload = dateOfUpload;
       this.machineStatues = machineStatues;
       this.usageFees = usageFees;
       this.machineReturnsMoney = machineReturnsMoney;
       this.totalTimeOfUse = totalTimeOfUse;
       this.prizeses = prizeses;
       this.lsLifteds = lsLifteds;
       this.repairs = repairs;
       this.permittedMachines = permittedMachines;
       this.userUseMachines = userUseMachines;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Machine_ID", unique=true, nullable=false)
    public Integer getMachineId() {
        return this.machineId;
    }
    
    public void setMachineId(Integer machineId) {
        this.machineId = machineId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Corner_Number", nullable=false)
    public Corners getCorners() {
        return this.corners;
    }
    
    public void setCorners(Corners corners) {
        this.corners = corners;
    }

    
    @Column(name="Machine_name", unique=true, nullable=false, length=45)
    public String getMachineName() {
        return this.machineName;
    }
    
    public void setMachineName(String machineName) {
        this.machineName = machineName;
    }

    
    @Column(name="Machine_type", unique=true, nullable=false, length=45)
    public String getMachineType() {
        return this.machineType;
    }
    
    public void setMachineType(String machineType) {
        this.machineType = machineType;
    }

    
    @Column(name="Machine_price", nullable=false, precision=12, scale=0)
    public float getMachinePrice() {
        return this.machinePrice;
    }
    
    public void setMachinePrice(float machinePrice) {
        this.machinePrice = machinePrice;
    }

    
    @Column(name="Total_number_of_prizes", nullable=false)
    public int getTotalNumberOfPrizes() {
        return this.totalNumberOfPrizes;
    }
    
    public void setTotalNumberOfPrizes(int totalNumberOfPrizes) {
        this.totalNumberOfPrizes = totalNumberOfPrizes;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Date_of_entry", nullable=false, length=10)
    public Date getDateOfEntry() {
        return this.dateOfEntry;
    }
    
    public void setDateOfEntry(Date dateOfEntry) {
        this.dateOfEntry = dateOfEntry;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Date_of_upload", nullable=false, length=10)
    public Date getDateOfUpload() {
        return this.dateOfUpload;
    }
    
    public void setDateOfUpload(Date dateOfUpload) {
        this.dateOfUpload = dateOfUpload;
    }

    
    @Column(name="Machine_statues", nullable=false, length=100)
    public String getMachineStatues() {
        return this.machineStatues;
    }
    
    public void setMachineStatues(String machineStatues) {
        this.machineStatues = machineStatues;
    }

    
    @Column(name="Usage_fees", nullable=false, precision=12, scale=0)
    public float getUsageFees() {
        return this.usageFees;
    }
    
    public void setUsageFees(float usageFees) {
        this.usageFees = usageFees;
    }

    
    @Column(name="Machine_returns_money", nullable=false, precision=12, scale=0)
    public float getMachineReturnsMoney() {
        return this.machineReturnsMoney;
    }
    
    public void setMachineReturnsMoney(float machineReturnsMoney) {
        this.machineReturnsMoney = machineReturnsMoney;
    }

    
    @Column(name="Total_time_of_use", precision=12, scale=0)
    public Float getTotalTimeOfUse() {
        return this.totalTimeOfUse;
    }
    
    public void setTotalTimeOfUse(Float totalTimeOfUse) {
        this.totalTimeOfUse = totalTimeOfUse;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="machine")
    public Set<Prizes> getPrizeses() {
        return this.prizeses;
    }
    
    public void setPrizeses(Set<Prizes> prizeses) {
        this.prizeses = prizeses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="machine")
    public Set<LsLifted> getLsLifteds() {
        return this.lsLifteds;
    }
    
    public void setLsLifteds(Set<LsLifted> lsLifteds) {
        this.lsLifteds = lsLifteds;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="machine")
    public Set<Repair> getRepairs() {
        return this.repairs;
    }
    
    public void setRepairs(Set<Repair> repairs) {
        this.repairs = repairs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="machine")
    public Set<PermittedMachine> getPermittedMachines() {
        return this.permittedMachines;
    }
    
    public void setPermittedMachines(Set<PermittedMachine> permittedMachines) {
        this.permittedMachines = permittedMachines;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="machine")
    public Set<UserUseMachine> getUserUseMachines() {
        return this.userUseMachines;
    }
    
    public void setUserUseMachines(Set<UserUseMachine> userUseMachines) {
        this.userUseMachines = userUseMachines;
    }




}


