package com.finalagc.www._1_2_MySql_DB_entities;
// Generated May 19, 2023 7:19:39 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MakeContract generated by hbm2java
 */
@Entity
@Table(name="make_contract"
    ,catalog="agc_db"
)
public class MakeContract  implements java.io.Serializable {


     private Integer makeContractId;
     private Contract contract;
     private Employee employee;
     private Date workEndDate;
     private Date workStartDate;

    public MakeContract() {
    }

	
    public MakeContract(Contract contract, Employee employee, Date workStartDate) {
        this.contract = contract;
        this.employee = employee;
        this.workStartDate = workStartDate;
    }
    public MakeContract(Contract contract, Employee employee, Date workEndDate, Date workStartDate) {
       this.contract = contract;
       this.employee = employee;
       this.workEndDate = workEndDate;
       this.workStartDate = workStartDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="make_contract_id", unique=true, nullable=false)
    public Integer getMakeContractId() {
        return this.makeContractId;
    }
    
    public void setMakeContractId(Integer makeContractId) {
        this.makeContractId = makeContractId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Contract_Id", nullable=false)
    public Contract getContract() {
        return this.contract;
    }
    
    public void setContract(Contract contract) {
        this.contract = contract;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EmployeeID", nullable=false)
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Work_end_date", length=10)
    public Date getWorkEndDate() {
        return this.workEndDate;
    }
    
    public void setWorkEndDate(Date workEndDate) {
        this.workEndDate = workEndDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Work_start_date", nullable=false, length=10)
    public Date getWorkStartDate() {
        return this.workStartDate;
    }
    
    public void setWorkStartDate(Date workStartDate) {
        this.workStartDate = workStartDate;
    }




}


