package com.finalagc.www._1_2_MySql_DB_entities;
// Generated May 19, 2023 7:19:39 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PermittedMachine generated by hbm2java
 */
@Entity
@Table(name="permitted_machine"
    ,catalog="agc_db"
)
public class PermittedMachine  implements java.io.Serializable {


     private Integer permittedMachineId;
     private Machine machine;
     private SubscriptionPackage subscriptionPackage;

    public PermittedMachine() {
    }

    public PermittedMachine(Machine machine, SubscriptionPackage subscriptionPackage) {
       this.machine = machine;
       this.subscriptionPackage = subscriptionPackage;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="permitted_machine_id", unique=true, nullable=false)
    public Integer getPermittedMachineId() {
        return this.permittedMachineId;
    }
    
    public void setPermittedMachineId(Integer permittedMachineId) {
        this.permittedMachineId = permittedMachineId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Machine_ID", nullable=false)
    public Machine getMachine() {
        return this.machine;
    }
    
    public void setMachine(Machine machine) {
        this.machine = machine;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Package_ID", nullable=false)
    public SubscriptionPackage getSubscriptionPackage() {
        return this.subscriptionPackage;
    }
    
    public void setSubscriptionPackage(SubscriptionPackage subscriptionPackage) {
        this.subscriptionPackage = subscriptionPackage;
    }




}


