package com.finalagc.www._1_2_MySql_DB_entities;
// Generated May 19, 2023 7:19:39 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Prizes generated by hbm2java
 */
@Entity
@Table(name="prizes"
    ,catalog="agc_db"
)
public class Prizes  implements java.io.Serializable {


     private int prizeId;
     private Machine machine;
     private String prizeName;
     private String prizeType;
     private Float prizePrice;
     private Set<CompetitionPrizes> competitionPrizeses = new HashSet<CompetitionPrizes>(0);
     private Set<UserWinPrize> userWinPrizes = new HashSet<UserWinPrize>(0);

    public Prizes() {
    }

	
    public Prizes(int prizeId, Machine machine) {
        this.prizeId = prizeId;
        this.machine = machine;
    }
    public Prizes(int prizeId, Machine machine, String prizeName, String prizeType, Float prizePrice, Set<CompetitionPrizes> competitionPrizeses, Set<UserWinPrize> userWinPrizes) {
       this.prizeId = prizeId;
       this.machine = machine;
       this.prizeName = prizeName;
       this.prizeType = prizeType;
       this.prizePrice = prizePrice;
       this.competitionPrizeses = competitionPrizeses;
       this.userWinPrizes = userWinPrizes;
    }
   
     @Id 

    
    @Column(name="Prize_ID", unique=true, nullable=false)
    public int getPrizeId() {
        return this.prizeId;
    }
    
    public void setPrizeId(int prizeId) {
        this.prizeId = prizeId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Machine_ID", nullable=false)
    public Machine getMachine() {
        return this.machine;
    }
    
    public void setMachine(Machine machine) {
        this.machine = machine;
    }

    
    @Column(name="Prize Name", length=45)
    public String getPrizeName() {
        return this.prizeName;
    }
    
    public void setPrizeName(String prizeName) {
        this.prizeName = prizeName;
    }

    
    @Column(name="Prize_type", length=45)
    public String getPrizeType() {
        return this.prizeType;
    }
    
    public void setPrizeType(String prizeType) {
        this.prizeType = prizeType;
    }

    
    @Column(name="Prize_price", precision=12, scale=0)
    public Float getPrizePrice() {
        return this.prizePrice;
    }
    
    public void setPrizePrice(Float prizePrice) {
        this.prizePrice = prizePrice;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="prizes")
    public Set<CompetitionPrizes> getCompetitionPrizeses() {
        return this.competitionPrizeses;
    }
    
    public void setCompetitionPrizeses(Set<CompetitionPrizes> competitionPrizeses) {
        this.competitionPrizeses = competitionPrizeses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="prizes")
    public Set<UserWinPrize> getUserWinPrizes() {
        return this.userWinPrizes;
    }
    
    public void setUserWinPrizes(Set<UserWinPrize> userWinPrizes) {
        this.userWinPrizes = userWinPrizes;
    }




}


