package com.finalagc.www._1_2_MySql_DB_entities;
// Generated May 19, 2023 7:19:39 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Shift generated by hbm2java
 */
@Entity
@Table(name="shift"
    ,catalog="agc_db"
    , uniqueConstraints = @UniqueConstraint(columnNames="Shift_Name") 
)
public class Shift  implements java.io.Serializable {


     private Integer shiftId;
     private String shiftName;
     private Date shiftStartTime;
     private Date shiftEndTime;
     private Set<EmployeeAttendanceTime> employeeAttendanceTimes = new HashSet<EmployeeAttendanceTime>(0);
     private Set<Employee> employees = new HashSet<Employee>(0);

    public Shift() {
    }

	
    public Shift(String shiftName, Date shiftStartTime, Date shiftEndTime) {
        this.shiftName = shiftName;
        this.shiftStartTime = shiftStartTime;
        this.shiftEndTime = shiftEndTime;
    }
    public Shift(String shiftName, Date shiftStartTime, Date shiftEndTime, Set<EmployeeAttendanceTime> employeeAttendanceTimes, Set<Employee> employees) {
       this.shiftName = shiftName;
       this.shiftStartTime = shiftStartTime;
       this.shiftEndTime = shiftEndTime;
       this.employeeAttendanceTimes = employeeAttendanceTimes;
       this.employees = employees;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ShiftID", unique=true, nullable=false)
    public Integer getShiftId() {
        return this.shiftId;
    }
    
    public void setShiftId(Integer shiftId) {
        this.shiftId = shiftId;
    }

    
    @Column(name="Shift_Name", unique=true, nullable=false, length=45)
    public String getShiftName() {
        return this.shiftName;
    }
    
    public void setShiftName(String shiftName) {
        this.shiftName = shiftName;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="Shift_Start_Time", nullable=false, length=8)
    public Date getShiftStartTime() {
        return this.shiftStartTime;
    }
    
    public void setShiftStartTime(Date shiftStartTime) {
        this.shiftStartTime = shiftStartTime;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="Shift_End_Time", nullable=false, length=8)
    public Date getShiftEndTime() {
        return this.shiftEndTime;
    }
    
    public void setShiftEndTime(Date shiftEndTime) {
        this.shiftEndTime = shiftEndTime;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="shift")
    public Set<EmployeeAttendanceTime> getEmployeeAttendanceTimes() {
        return this.employeeAttendanceTimes;
    }
    
    public void setEmployeeAttendanceTimes(Set<EmployeeAttendanceTime> employeeAttendanceTimes) {
        this.employeeAttendanceTimes = employeeAttendanceTimes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="shift")
    public Set<Employee> getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Set<Employee> employees) {
        this.employees = employees;
    }




}


