package com.finalagc.www._1_2_MySql_DB_entities;
// Generated May 19, 2023 7:19:39 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * SubscriptionPackage generated by hbm2java
 */
@Entity
@Table(name="subscription_package"
    ,catalog="agc_db"
    , uniqueConstraints = @UniqueConstraint(columnNames="Package_name") 
)
public class SubscriptionPackage  implements java.io.Serializable {


     private Integer packageId;
     private String packageName;
     private float packagePrice;
     private int packageDuration;
     private int packageLimits;
     private Set<PermittedMachine> permittedMachines = new HashSet<PermittedMachine>(0);
     private Set<UserSubscription> userSubscriptions = new HashSet<UserSubscription>(0);

    public SubscriptionPackage() {
    }

	
    public SubscriptionPackage(String packageName, float packagePrice, int packageDuration, int packageLimits) {
        this.packageName = packageName;
        this.packagePrice = packagePrice;
        this.packageDuration = packageDuration;
        this.packageLimits = packageLimits;
    }
    public SubscriptionPackage(String packageName, float packagePrice, int packageDuration, int packageLimits, Set<PermittedMachine> permittedMachines, Set<UserSubscription> userSubscriptions) {
       this.packageName = packageName;
       this.packagePrice = packagePrice;
       this.packageDuration = packageDuration;
       this.packageLimits = packageLimits;
       this.permittedMachines = permittedMachines;
       this.userSubscriptions = userSubscriptions;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name=" Package_ID", unique=true, nullable=false)
    public Integer getPackageId() {
        return this.packageId;
    }
    
    public void setPackageId(Integer packageId) {
        this.packageId = packageId;
    }

    
    @Column(name="Package_name", unique=true, nullable=false, length=45)
    public String getPackageName() {
        return this.packageName;
    }
    
    public void setPackageName(String packageName) {
        this.packageName = packageName;
    }

    
    @Column(name="Package_price", nullable=false, precision=12, scale=0)
    public float getPackagePrice() {
        return this.packagePrice;
    }
    
    public void setPackagePrice(float packagePrice) {
        this.packagePrice = packagePrice;
    }

    
    @Column(name="Package_Duration", nullable=false)
    public int getPackageDuration() {
        return this.packageDuration;
    }
    
    public void setPackageDuration(int packageDuration) {
        this.packageDuration = packageDuration;
    }

    
    @Column(name="Package_limits", nullable=false)
    public int getPackageLimits() {
        return this.packageLimits;
    }
    
    public void setPackageLimits(int packageLimits) {
        this.packageLimits = packageLimits;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="subscriptionPackage")
    public Set<PermittedMachine> getPermittedMachines() {
        return this.permittedMachines;
    }
    
    public void setPermittedMachines(Set<PermittedMachine> permittedMachines) {
        this.permittedMachines = permittedMachines;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="subscriptionPackage")
    public Set<UserSubscription> getUserSubscriptions() {
        return this.userSubscriptions;
    }
    
    public void setUserSubscriptions(Set<UserSubscription> userSubscriptions) {
        this.userSubscriptions = userSubscriptions;
    }




}


