package com.finalagc.www._1_2_MySql_DB_entities;
// Generated May 19, 2023 7:19:39 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tasks generated by hbm2java
 */
@Entity
@Table(name="tasks"
    ,catalog="agc_db"
)
public class Tasks  implements java.io.Serializable {


     private int taskId;
     private Employee employee;
     private String taskDescription;
     private Date startingDate;
     private Date finishingDate;
     private int duration;
     private String taskTitle;
     private String taskStatues;

    public Tasks() {
    }

    public Tasks(int taskId, Employee employee, String taskDescription, Date startingDate, Date finishingDate, int duration, String taskTitle, String taskStatues) {
       this.taskId = taskId;
       this.employee = employee;
       this.taskDescription = taskDescription;
       this.startingDate = startingDate;
       this.finishingDate = finishingDate;
       this.duration = duration;
       this.taskTitle = taskTitle;
       this.taskStatues = taskStatues;
    }
   
     @Id 

    
    @Column(name="Task_id", unique=true, nullable=false)
    public int getTaskId() {
        return this.taskId;
    }
    
    public void setTaskId(int taskId) {
        this.taskId = taskId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Employee_EmployeeID", nullable=false)
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

    
    @Column(name="Task_description", nullable=false)
    public String getTaskDescription() {
        return this.taskDescription;
    }
    
    public void setTaskDescription(String taskDescription) {
        this.taskDescription = taskDescription;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="starting_date", nullable=false, length=19)
    public Date getStartingDate() {
        return this.startingDate;
    }
    
    public void setStartingDate(Date startingDate) {
        this.startingDate = startingDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Finishing_date", nullable=false, length=19)
    public Date getFinishingDate() {
        return this.finishingDate;
    }
    
    public void setFinishingDate(Date finishingDate) {
        this.finishingDate = finishingDate;
    }

    
    @Column(name="Duration", nullable=false)
    public int getDuration() {
        return this.duration;
    }
    
    public void setDuration(int duration) {
        this.duration = duration;
    }

    
    @Column(name="Task_title", nullable=false, length=150)
    public String getTaskTitle() {
        return this.taskTitle;
    }
    
    public void setTaskTitle(String taskTitle) {
        this.taskTitle = taskTitle;
    }

    
    @Column(name="Task_statues", nullable=false, length=11)
    public String getTaskStatues() {
        return this.taskStatues;
    }
    
    public void setTaskStatues(String taskStatues) {
        this.taskStatues = taskStatues;
    }




}


