package com.finalagc.www._1_2_MySql_DB_entities;
// Generated May 19, 2023 7:19:39 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserWinCompetition generated by hbm2java
 */
@Entity
@Table(name="user_win_competition"
    ,catalog="agc_db"
)
public class UserWinCompetition  implements java.io.Serializable {


     private Integer winnerId;
     private Competition competition;
     private User user;
     private int rank;

    public UserWinCompetition() {
    }

    public UserWinCompetition(Competition competition, User user, int rank) {
       this.competition = competition;
       this.user = user;
       this.rank = rank;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="winner_id", unique=true, nullable=false)
    public Integer getWinnerId() {
        return this.winnerId;
    }
    
    public void setWinnerId(Integer winnerId) {
        this.winnerId = winnerId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Competition_Id", nullable=false)
    public Competition getCompetition() {
        return this.competition;
    }
    
    public void setCompetition(Competition competition) {
        this.competition = competition;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="UserID", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="Rank", nullable=false)
    public int getRank() {
        return this.rank;
    }
    
    public void setRank(int rank) {
        this.rank = rank;
    }




}


