package com.finalagc.www._1_2_MySql_DB_entities;
// Generated May 19, 2023 7:19:39 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserSubscription generated by hbm2java
 */
@Entity
@Table(name="user_subscription"
    ,catalog="agc_db"
)
public class UserSubscription  implements java.io.Serializable {


     private Integer userSubscriptionId;
     private SubscriptionPackage subscriptionPackage;
     private User user;
     private Date subscriptionDate;

    public UserSubscription() {
    }

    public UserSubscription(SubscriptionPackage subscriptionPackage, User user, Date subscriptionDate) {
       this.subscriptionPackage = subscriptionPackage;
       this.user = user;
       this.subscriptionDate = subscriptionDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="user_subscription_id", unique=true, nullable=false)
    public Integer getUserSubscriptionId() {
        return this.userSubscriptionId;
    }
    
    public void setUserSubscriptionId(Integer userSubscriptionId) {
        this.userSubscriptionId = userSubscriptionId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Package_ID", nullable=false)
    public SubscriptionPackage getSubscriptionPackage() {
        return this.subscriptionPackage;
    }
    
    public void setSubscriptionPackage(SubscriptionPackage subscriptionPackage) {
        this.subscriptionPackage = subscriptionPackage;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="UserID", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Subscription_date", nullable=false, length=19)
    public Date getSubscriptionDate() {
        return this.subscriptionDate;
    }
    
    public void setSubscriptionDate(Date subscriptionDate) {
        this.subscriptionDate = subscriptionDate;
    }




}


