package com.agc.www._1_2_MySql_DB_entities;
// Generated May 17, 2023 11:14:37 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Competition generated by hbm2java
 */
@Entity
@Table(name="competition"
    ,catalog="agc_db"
)
public class Competition  implements java.io.Serializable {


     private Integer competitionId;
     private Employee employee;
     private String competitionName;
     private Date startDate;
     private Date endDate;
     private Set<CompetitionPrizes> competitionPrizeses = new HashSet<CompetitionPrizes>(0);
     private Set<UserWinCompetition> userWinCompetitions = new HashSet<UserWinCompetition>(0);
     private Set<JoinedUser> joinedUsers = new HashSet<JoinedUser>(0);

    public Competition() {
    }

	
    public Competition(Employee employee) {
        this.employee = employee;
    }
    public Competition(Employee employee, String competitionName, Date startDate, Date endDate, Set<CompetitionPrizes> competitionPrizeses, Set<UserWinCompetition> userWinCompetitions, Set<JoinedUser> joinedUsers) {
       this.employee = employee;
       this.competitionName = competitionName;
       this.startDate = startDate;
       this.endDate = endDate;
       this.competitionPrizeses = competitionPrizeses;
       this.userWinCompetitions = userWinCompetitions;
       this.joinedUsers = joinedUsers;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Competition_Id", unique=true, nullable=false)
    public Integer getCompetitionId() {
        return this.competitionId;
    }
    
    public void setCompetitionId(Integer competitionId) {
        this.competitionId = competitionId;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="EmployeeID", nullable=false)
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

    
    @Column(name="Competition_name", length=45)
    public String getCompetitionName() {
        return this.competitionName;
    }
    
    public void setCompetitionName(String competitionName) {
        this.competitionName = competitionName;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Start_date", length=10)
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="End_date", length=10)
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="competition")
    public Set<CompetitionPrizes> getCompetitionPrizeses() {
        return this.competitionPrizeses;
    }
    
    public void setCompetitionPrizeses(Set<CompetitionPrizes> competitionPrizeses) {
        this.competitionPrizeses = competitionPrizeses;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="competition")
    public Set<UserWinCompetition> getUserWinCompetitions() {
        return this.userWinCompetitions;
    }
    
    public void setUserWinCompetitions(Set<UserWinCompetition> userWinCompetitions) {
        this.userWinCompetitions = userWinCompetitions;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="competition")
    public Set<JoinedUser> getJoinedUsers() {
        return this.joinedUsers;
    }
    
    public void setJoinedUsers(Set<JoinedUser> joinedUsers) {
        this.joinedUsers = joinedUsers;
    }




}


