package com.agc.www._1_2_MySql_DB_entities;
// Generated May 17, 2023 11:14:37 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CompetitionPrizes generated by hbm2java
 */
@Entity
@Table(name="competition_prizes"
    ,catalog="agc_db"
)
public class CompetitionPrizes  implements java.io.Serializable {


     private int competitionPrizesId;
     private Competition competition;
     private Prizes prizes;
     private int prizeRank;

    public CompetitionPrizes() {
    }

    public CompetitionPrizes(int competitionPrizesId, Competition competition, Prizes prizes, int prizeRank) {
       this.competitionPrizesId = competitionPrizesId;
       this.competition = competition;
       this.prizes = prizes;
       this.prizeRank = prizeRank;
    }
   
     @Id 

    
    @Column(name="competition_prizes_id", unique=true, nullable=false)
    public int getCompetitionPrizesId() {
        return this.competitionPrizesId;
    }
    
    public void setCompetitionPrizesId(int competitionPrizesId) {
        this.competitionPrizesId = competitionPrizesId;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="Competition_Id", nullable=false)
    public Competition getCompetition() {
        return this.competition;
    }
    
    public void setCompetition(Competition competition) {
        this.competition = competition;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="Prize_ID", nullable=false)
    public Prizes getPrizes() {
        return this.prizes;
    }
    
    public void setPrizes(Prizes prizes) {
        this.prizes = prizes;
    }

    
    @Column(name="Prize_Rank", nullable=false)
    public int getPrizeRank() {
        return this.prizeRank;
    }
    
    public void setPrizeRank(int prizeRank) {
        this.prizeRank = prizeRank;
    }




}


