package com.agc.www._1_2_MySql_DB_entities;
// Generated May 17, 2023 11:14:37 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmployeeAttendanceTime generated by hbm2java
 */
@Entity
@Table(name="employee_attendance_time"
    ,catalog="agc_db"
)
public class EmployeeAttendanceTime  implements java.io.Serializable {


     private int employeeAttendanceId;
     private Employee employee;
     private Shift shift;
     private String attendanceStatus;
     private Date attendanceDateTime;
     private Date departureDateTime;

    public EmployeeAttendanceTime() {
    }

    public EmployeeAttendanceTime(int employeeAttendanceId, Employee employee, Shift shift, String attendanceStatus, Date attendanceDateTime, Date departureDateTime) {
       this.employeeAttendanceId = employeeAttendanceId;
       this.employee = employee;
       this.shift = shift;
       this.attendanceStatus = attendanceStatus;
       this.attendanceDateTime = attendanceDateTime;
       this.departureDateTime = departureDateTime;
    }
   
     @Id 

    
    @Column(name="employee_attendance_id", unique=true, nullable=false)
    public int getEmployeeAttendanceId() {
        return this.employeeAttendanceId;
    }
    
    public void setEmployeeAttendanceId(int employeeAttendanceId) {
        this.employeeAttendanceId = employeeAttendanceId;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="EmployeeID", nullable=false)
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="ShiftID", nullable=false)
    public Shift getShift() {
        return this.shift;
    }
    
    public void setShift(Shift shift) {
        this.shift = shift;
    }

    
    @Column(name="Attendance_status", nullable=false, length=6)
    public String getAttendanceStatus() {
        return this.attendanceStatus;
    }
    
    public void setAttendanceStatus(String attendanceStatus) {
        this.attendanceStatus = attendanceStatus;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Attendance_date_time", nullable=false, length=19)
    public Date getAttendanceDateTime() {
        return this.attendanceDateTime;
    }
    
    public void setAttendanceDateTime(Date attendanceDateTime) {
        this.attendanceDateTime = attendanceDateTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Departure_date_time", nullable=false, length=19)
    public Date getDepartureDateTime() {
        return this.departureDateTime;
    }
    
    public void setDepartureDateTime(Date departureDateTime) {
        this.departureDateTime = departureDateTime;
    }




}


