package com.agc.www._1_2_MySql_DB_entities;
// Generated May 17, 2023 11:14:37 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Jobs generated by hbm2java
 */
@Entity
@Table(name="jobs"
    ,catalog="agc_db"
    , uniqueConstraints = @UniqueConstraint(columnNames="Job_title") 
)
public class Jobs  implements java.io.Serializable {


     private Integer jobId;
     private String jobTitle;
     private Set<Employee> employees = new HashSet<Employee>(0);

    public Jobs() {
    }

	
    public Jobs(String jobTitle) {
        this.jobTitle = jobTitle;
    }
    public Jobs(String jobTitle, Set<Employee> employees) {
       this.jobTitle = jobTitle;
       this.employees = employees;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="JobId", unique=true, nullable=false)
    public Integer getJobId() {
        return this.jobId;
    }
    
    public void setJobId(Integer jobId) {
        this.jobId = jobId;
    }

    
    @Column(name="Job_title", unique=true, nullable=false, length=45)
    public String getJobTitle() {
        return this.jobTitle;
    }
    
    public void setJobTitle(String jobTitle) {
        this.jobTitle = jobTitle;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="jobs")
    public Set<Employee> getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Set<Employee> employees) {
        this.employees = employees;
    }




}


