package com.agc.www._1_2_MySql_DB_entities;
// Generated May 17, 2023 11:14:37 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Contract generated by hbm2java
 */
@Entity
@Table(name="contract"
    ,catalog="agc_db"
)
public class Contract  implements java.io.Serializable {


     private Integer contractId;
     private String employmentContractStatus;
     private String employmentStatus;
     private float mainSalary;
     private float annualSalaryIncreaseRate;
     private Float salaryAfterIncrease;
     private Set<MakeContract> makeContracts = new HashSet<MakeContract>(0);
     private Set<TakSalary> takSalaries = new HashSet<TakSalary>(0);

    public Contract() {
    }

	
    public Contract(String employmentContractStatus, String employmentStatus, float mainSalary, float annualSalaryIncreaseRate) {
        this.employmentContractStatus = employmentContractStatus;
        this.employmentStatus = employmentStatus;
        this.mainSalary = mainSalary;
        this.annualSalaryIncreaseRate = annualSalaryIncreaseRate;
    }
    public Contract(String employmentContractStatus, String employmentStatus, float mainSalary, float annualSalaryIncreaseRate, Float salaryAfterIncrease, Set<MakeContract> makeContracts, Set<TakSalary> takSalaries) {
       this.employmentContractStatus = employmentContractStatus;
       this.employmentStatus = employmentStatus;
       this.mainSalary = mainSalary;
       this.annualSalaryIncreaseRate = annualSalaryIncreaseRate;
       this.salaryAfterIncrease = salaryAfterIncrease;
       this.makeContracts = makeContracts;
       this.takSalaries = takSalaries;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Contract_Id", unique=true, nullable=false)
    public Integer getContractId() {
        return this.contractId;
    }
    
    public void setContractId(Integer contractId) {
        this.contractId = contractId;
    }

    
    @Column(name="Employment_contract_status", nullable=false, length=21)
    public String getEmploymentContractStatus() {
        return this.employmentContractStatus;
    }
    
    public void setEmploymentContractStatus(String employmentContractStatus) {
        this.employmentContractStatus = employmentContractStatus;
    }

    
    @Column(name="Employment_status", nullable=false, length=9)
    public String getEmploymentStatus() {
        return this.employmentStatus;
    }
    
    public void setEmploymentStatus(String employmentStatus) {
        this.employmentStatus = employmentStatus;
    }

    
    @Column(name="Main_salary", nullable=false, precision=12, scale=0)
    public float getMainSalary() {
        return this.mainSalary;
    }
    
    public void setMainSalary(float mainSalary) {
        this.mainSalary = mainSalary;
    }

    
    @Column(name="Annual_salary_increase_rate", nullable=false, precision=12, scale=0)
    public float getAnnualSalaryIncreaseRate() {
        return this.annualSalaryIncreaseRate;
    }
    
    public void setAnnualSalaryIncreaseRate(float annualSalaryIncreaseRate) {
        this.annualSalaryIncreaseRate = annualSalaryIncreaseRate;
    }

    
    @Column(name="Salary_after_Increase", precision=12, scale=0)
    public Float getSalaryAfterIncrease() {
        return this.salaryAfterIncrease;
    }
    
    public void setSalaryAfterIncrease(Float salaryAfterIncrease) {
        this.salaryAfterIncrease = salaryAfterIncrease;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="contract")
    public Set<MakeContract> getMakeContracts() {
        return this.makeContracts;
    }
    
    public void setMakeContracts(Set<MakeContract> makeContracts) {
        this.makeContracts = makeContracts;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="contract")
    public Set<TakSalary> getTakSalaries() {
        return this.takSalaries;
    }
    
    public void setTakSalaries(Set<TakSalary> takSalaries) {
        this.takSalaries = takSalaries;
    }




}


