package com.agc.www._1_2_MySql_DB_entities;
// Generated May 17, 2023 11:14:37 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EmployeePhoneNumbers generated by hbm2java
 */
@Entity
@Table(name="employee_phone_numbers"
    ,catalog="agc_db"
)
public class EmployeePhoneNumbers  implements java.io.Serializable {


     private int phoneNumber;
     private Employee employee;

    public EmployeePhoneNumbers() {
    }

    public EmployeePhoneNumbers(int phoneNumber, Employee employee) {
       this.phoneNumber = phoneNumber;
       this.employee = employee;
    }
   
     @Id 

    
    @Column(name="Phone_number", unique=true, nullable=false)
    public int getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(int phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="EmployeeID", nullable=false)
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }




}


