package com.agc.www._1_2_MySql_DB_entities;
// Generated May 17, 2023 11:14:37 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Images generated by hbm2java
 */
@Entity
@Table(name="images"
    ,catalog="agc_db"
)
public class Images  implements java.io.Serializable {


     private int imageId;
     private byte[] image;
     private Integer imageOwnerId;

    public Images() {
    }

	
    public Images(int imageId) {
        this.imageId = imageId;
    }
    public Images(int imageId, byte[] image, Integer imageOwnerId) {
       this.imageId = imageId;
       this.image = image;
       this.imageOwnerId = imageOwnerId;
    }
   
     @Id 

    
    @Column(name="image_id", unique=true, nullable=false)
    public int getImageId() {
        return this.imageId;
    }
    
    public void setImageId(int imageId) {
        this.imageId = imageId;
    }

    
    @Column(name="image")
    public byte[] getImage() {
        return this.image;
    }
    
    public void setImage(byte[] image) {
        this.image = image;
    }

    
    @Column(name="image_owner_id")
    public Integer getImageOwnerId() {
        return this.imageOwnerId;
    }
    
    public void setImageOwnerId(Integer imageOwnerId) {
        this.imageOwnerId = imageOwnerId;
    }




}


