package com.agc.www._1_2_MySql_DB_entities;
// Generated May 17, 2023 11:14:37 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PermittedMachine generated by hbm2java
 */
@Entity
@Table(name="permitted_machine"
    ,catalog="agc_db"
)
public class PermittedMachine  implements java.io.Serializable {


     private int permittedMachineId;
     private Machine machine;
     private SubscriptionPackage subscriptionPackage;

    public PermittedMachine() {
    }

    public PermittedMachine(int permittedMachineId, Machine machine, SubscriptionPackage subscriptionPackage) {
       this.permittedMachineId = permittedMachineId;
       this.machine = machine;
       this.subscriptionPackage = subscriptionPackage;
    }
   
     @Id 

    
    @Column(name="permitted_machine_id", unique=true, nullable=false)
    public int getPermittedMachineId() {
        return this.permittedMachineId;
    }
    
    public void setPermittedMachineId(int permittedMachineId) {
        this.permittedMachineId = permittedMachineId;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="Machine_ID", nullable=false)
    public Machine getMachine() {
        return this.machine;
    }
    
    public void setMachine(Machine machine) {
        this.machine = machine;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="Package_ID", nullable=false)
    public SubscriptionPackage getSubscriptionPackage() {
        return this.subscriptionPackage;
    }
    
    public void setSubscriptionPackage(SubscriptionPackage subscriptionPackage) {
        this.subscriptionPackage = subscriptionPackage;
    }




}


