package com.agc.www._1_2_MySql_DB_entities;
// Generated May 17, 2023 11:14:37 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TakSalary generated by hbm2java
 */
@Entity
@Table(name="tak_salary"
    ,catalog="agc_db"
)
public class TakSalary  implements java.io.Serializable {


     private Integer takSalaryId;
     private Contract contract;
     private Employee employee;
     private Float totalSalary;
     private Date dateOfReceipt;

    public TakSalary() {
    }

	
    public TakSalary(Contract contract, Employee employee, Date dateOfReceipt) {
        this.contract = contract;
        this.employee = employee;
        this.dateOfReceipt = dateOfReceipt;
    }
    public TakSalary(Contract contract, Employee employee, Float totalSalary, Date dateOfReceipt) {
       this.contract = contract;
       this.employee = employee;
       this.totalSalary = totalSalary;
       this.dateOfReceipt = dateOfReceipt;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="tak_salary_id", unique=true, nullable=false)
    public Integer getTakSalaryId() {
        return this.takSalaryId;
    }
    
    public void setTakSalaryId(Integer takSalaryId) {
        this.takSalaryId = takSalaryId;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="Contract_Id", nullable=false)
    public Contract getContract() {
        return this.contract;
    }
    
    public void setContract(Contract contract) {
        this.contract = contract;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="EmployeeID", nullable=false)
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

    
    @Column(name="Total_salary", precision=12, scale=0)
    public Float getTotalSalary() {
        return this.totalSalary;
    }
    
    public void setTotalSalary(Float totalSalary) {
        this.totalSalary = totalSalary;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Date_of_receipt", nullable=false, length=10)
    public Date getDateOfReceipt() {
        return this.dateOfReceipt;
    }
    
    public void setDateOfReceipt(Date dateOfReceipt) {
        this.dateOfReceipt = dateOfReceipt;
    }




}


