package com.agc.www._1_2_MySql_DB_entities;
// Generated May 17, 2023 11:14:37 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserWinPrize generated by hbm2java
 */
@Entity
@Table(name="user_win_prize"
    ,catalog="agc_db"
)
public class UserWinPrize  implements java.io.Serializable {


     private int userWinPrizeId;
     private Prizes prizes;
     private User user;
     private Date drawTiming;

    public UserWinPrize() {
    }

	
    public UserWinPrize(int userWinPrizeId, Prizes prizes, User user) {
        this.userWinPrizeId = userWinPrizeId;
        this.prizes = prizes;
        this.user = user;
    }
    public UserWinPrize(int userWinPrizeId, Prizes prizes, User user, Date drawTiming) {
       this.userWinPrizeId = userWinPrizeId;
       this.prizes = prizes;
       this.user = user;
       this.drawTiming = drawTiming;
    }
   
     @Id 

    
    @Column(name="user_win_prize_id", unique=true, nullable=false)
    public int getUserWinPrizeId() {
        return this.userWinPrizeId;
    }
    
    public void setUserWinPrizeId(int userWinPrizeId) {
        this.userWinPrizeId = userWinPrizeId;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="Prize_ID", nullable=false)
    public Prizes getPrizes() {
        return this.prizes;
    }
    
    public void setPrizes(Prizes prizes) {
        this.prizes = prizes;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="UserID", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Draw_timing", length=19)
    public Date getDrawTiming() {
        return this.drawTiming;
    }
    
    public void setDrawTiming(Date drawTiming) {
        this.drawTiming = drawTiming;
    }




}


