package com.agc.www._1_2_MySql_DB_entities;
// Generated May 17, 2023 11:14:37 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserUseMachine generated by hbm2java
 */
@Entity
@Table(name="user_use_machine"
    ,catalog="agc_db"
)
public class UserUseMachine  implements java.io.Serializable {


     private int userUseMachineId;
     private Machine machine;
     private User user;
     private Date timeOfUse;

    public UserUseMachine() {
    }

    public UserUseMachine(int userUseMachineId, Machine machine, User user, Date timeOfUse) {
       this.userUseMachineId = userUseMachineId;
       this.machine = machine;
       this.user = user;
       this.timeOfUse = timeOfUse;
    }
   
     @Id 

    
    @Column(name="user_use_machine_id", unique=true, nullable=false)
    public int getUserUseMachineId() {
        return this.userUseMachineId;
    }
    
    public void setUserUseMachineId(int userUseMachineId) {
        this.userUseMachineId = userUseMachineId;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="Machine_ID", nullable=false)
    public Machine getMachine() {
        return this.machine;
    }
    
    public void setMachine(Machine machine) {
        this.machine = machine;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="UserID", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Time_of_use", nullable=false, length=19)
    public Date getTimeOfUse() {
        return this.timeOfUse;
    }
    
    public void setTimeOfUse(Date timeOfUse) {
        this.timeOfUse = timeOfUse;
    }




}


