package com.agc.www._1_2_MySql_DB_entities;
// Generated May 17, 2023 11:14:37 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserPhonNumber generated by hbm2java
 */
@Entity
@Table(name="user_phon_number"
    ,catalog="agc_db"
)
public class UserPhonNumber  implements java.io.Serializable {


     private int phoneNumber;
     private User user;

    public UserPhonNumber() {
    }

    public UserPhonNumber(int phoneNumber, User user) {
       this.phoneNumber = phoneNumber;
       this.user = user;
    }
   
     @Id 

    
    @Column(name="Phone_number", unique=true, nullable=false)
    public int getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(int phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="UserID", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }




}


