package com.agc.www._1_2_MySql_DB_entities;
// Generated May 17, 2023 11:14:37 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VisitCorner generated by hbm2java
 */
@Entity
@Table(name="visit_corner"
    ,catalog="agc_db"
)
public class VisitCorner  implements java.io.Serializable {


     private int visitCornerId;
     private Corners corners;
     private User user;
     private Date timeOfEntry;
     private Date timeOfGo;

    public VisitCorner() {
    }

	
    public VisitCorner(int visitCornerId, Corners corners, User user, Date timeOfEntry) {
        this.visitCornerId = visitCornerId;
        this.corners = corners;
        this.user = user;
        this.timeOfEntry = timeOfEntry;
    }
    public VisitCorner(int visitCornerId, Corners corners, User user, Date timeOfEntry, Date timeOfGo) {
       this.visitCornerId = visitCornerId;
       this.corners = corners;
       this.user = user;
       this.timeOfEntry = timeOfEntry;
       this.timeOfGo = timeOfGo;
    }
   
     @Id 

    
    @Column(name="visit_corner_id", unique=true, nullable=false)
    public int getVisitCornerId() {
        return this.visitCornerId;
    }
    
    public void setVisitCornerId(int visitCornerId) {
        this.visitCornerId = visitCornerId;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="Corner_Number", nullable=false)
    public Corners getCorners() {
        return this.corners;
    }
    
    public void setCorners(Corners corners) {
        this.corners = corners;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="UserID", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Time_of_entry", nullable=false, length=19)
    public Date getTimeOfEntry() {
        return this.timeOfEntry;
    }
    
    public void setTimeOfEntry(Date timeOfEntry) {
        this.timeOfEntry = timeOfEntry;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Time_of_go", length=19)
    public Date getTimeOfGo() {
        return this.timeOfGo;
    }
    
    public void setTimeOfGo(Date timeOfGo) {
        this.timeOfGo = timeOfGo;
    }




}


